# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'gaiden' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'AppAuth', :git => 'https://github.com/tobiastimm/AppAuth-iOS.git'

  # Pods for gaiden

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'gaidenTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'gaiden-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for gaiden-tvOS

  target 'gaiden-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
